import Foundation

/// The short title of a Meeting, generated by the model from the Summary.
public enum MeetingTitle {
    public static let maxWords = 6

    public static func request(summary: String, language: String) -> [ChatMessage] {
        [
            ChatMessage(role: .system, content: """
                Write the title of a meeting from its summary: at most \(maxWords) words, \
                in \(Language.name(language)), no date, no quotes and no final period. \
                Reply with the title only.
                """),
            ChatMessage(role: .user, content: summary),
        ]
    }

    /// First line with words, without Markdown headings, "Title:" prefixes, quotes, bold
    /// and final punctuation, at most `maxWords` words. `nil` if nothing is left.
    public static func clean(_ reply: String) -> String? {
        guard var line = reply.components(separatedBy: .newlines)
            .first(where: { !$0.trimmingCharacters(in: .whitespaces).isEmpty })
        else { return nil }

        // Headings, bold, quotes and prefixes can appear in any order
        // ("**Title:** …", "## Title: \"…\""): they are removed until nothing changes.
        let wrapping = CharacterSet(charactersIn: "#\"'“”‘’«»*_`").union(.whitespaces)
        var previous = ""
        while line != previous {
            previous = line
            line = line.trimmingCharacters(in: wrapping)
            for prefix in ["title:", "titolo:"] where line.lowercased().hasPrefix(prefix) {
                line.removeFirst(prefix.count)
            }
            line = line.trimmingCharacters(in: CharacterSet(charactersIn: ".!;:,").union(wrapping))
        }

        let words = line.split(whereSeparator: \.isWhitespace).prefix(maxWords)
        return words.isEmpty ? nil : words.joined(separator: " ")
    }
}
